### ISSUE TITLE
Uploading archives with releaser fails once in a while

### ISSUE THREAD

**Issue by epsilon-0** [pyTooling/Actions#49] opened 2022-06-18 23:20 UTC
I am using the `releaser` action with `pyTooling/Actions/releaser@r0` and it seems to be failing at uploading archives every once in a while.

The github action where this behaviour is  observed - https://github.com/OBSD-Homelab/openbsd-builder/actions

Example of a failed run - https://github.com/OBSD-Homelab/openbsd-builder/runs/6928392293?check_suite_focus=true
Example of a passing run - https://github.com/OBSD-Homelab/openbsd-builder/runs/6944587241?check_suite_focus=true

Both runs are scheduled runs, daily at `0 0 * * *`, so there is no code change between the two actions.

Let me know what else I should add to this report.

**Comment by Paebbels** [comment] 2022-06-19 11:53
This is a duplicate of #48, right?

**Comment by kikmon** [comment] 2022-06-24 01:14
Looks very similar to it
Any progress on the retry support ?

**Comment by epsilon-0** [comment] 2022-06-24 01:17
Kind of does. But I don't know what exactly is happening here.

**Comment by umarcor** [comment] 2022-06-28 11:57
Let's track this issue in #48.

**Closed by umarcor** 2022-06-28 11:57 UTC
Labels: Duplicate, Releaser
